services:
  ontology-generation-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - MONGODB_COLNAME=${MONGODB_COLNAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_LARGE=${OPENAI_MODEL_LARGE}
      - OPENAI_MODEL_SMALL${OPENAI_MODEL_SMALL}
      - OPENAI_MODEL_NANO=${OPENAI_MODEL_NANO}
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 